let str = 'abcdefg'
console.log(str.slice(1))
console.log(str.slice(1, 0))
console.log(str.slice(1, 1))
console.log(str.slice(1, 2))
console.log(str.slice(0))
console.log(str.slice(0, 0))
console.log(str.slice(0, 1))
console.log(str.slice(0, 2))
console.log(str.slice(-1))
console.log(str.slice(-4))

console.log('--------------------')
console.log(str.slice(-1))
console.log(str.slice(-2))
console.log(str.slice(-1, 1))
console.log(str.slice(-5, 5))
console.log(str.slice(-5, -1))
console.log(str.slice(5, -1))
