// Generated by CoffeeScript 2.1.0
(function() {
  var arr, i, len, test, val;

  console.log("test");

  test = "abc";

  console.log(test);

  arr = [1, 2, 3, 4, 5];

  for (i = 0, len = arr.length; i < len; i++) {
    val = arr[i];
    console.log(val);
  }

  arr.forEach(function(e) {
    return console.log(e);
  });

}).call(this);
